### ISSUE TITLE
SQLAlchemy Panel broken; relies on removed `json_available`

### ISSUE THREAD

**Issue by joelburton** [mgood/flask-debugtoolbar#136]
The latest version of Flask, 1.1.0, finally removed the deprecated `flask.json_available`, which is used in the sqlalchemy panel.

This is already fixed in GH, but the latest version at pypi is still 0.10.

Is there something we can do to help test/release 0.11?

**Comment by leblancfg** [comment]
See related [issue in the cookiecutter-flask](https://github.com/cookiecutter-flask/cookiecutter-flask/issues/517) repo.

Taking a look at the [Flask changelog](https://flask.palletsprojects.com/en/1.1.x/changelog/?highlight=json_available), we see:

>### Version 1.1.1
>
>*Released 2019-07-08*
>
>    The flask.json_available flag was added back for compatibility with some extensions. It will raise a deprecation warning when used, and will be removed in version 2.0.0. [#3288](https://github.com/pallets/flask/issues/3288)

Flask version where the method was removed is 1.1.0.

## Affected lines
### Quick fix
`setup.py` needs to exclude flask version 1.1.0

https://github.com/mgood/flask-debugtoolbar/blob/d852042ccb68d0507e0ef8d9e0d53287ca766f3b/setup.py#L33

**Comment by jeffwidman** [comment]
This is no longer needed since I pushed a `0.11` release (and unfortunately this wouldn't have really solved the issue anyway since the root problem had already been fixed here on github, just hadn't been pushed to Pypi). Sorry for the delay here, I plan to be a bit more active going forward on this project since it's still very useful.
