### ISSUE TITLE
Toolbar does not show when no body tag is present

### ISSUE THREAD

**Issue by mkzero** [mgood/flask-debugtoolbar#79]
Omitting the body tag is a valid practice in HTML and when not using any body tag the toolbar simply does not show.

The toolbar should at least log something to tell the developer why it is currently not showing up or better just be injected somewhere else when the body tag is missing.

**Comment by mgood** [comment]
Yeah, I've just merged #20 to add a warning when the `</body>` tag isn't present. I've left the check for `</body>` in so far to make sure the toolbar is only inserted into complete HTML pages. I've been thinking how to remove that requirement, but it could screw up a few situations.

Some apps may accidentally serve non-HTML pages with "Content-Type: text/html". I'm less concerned about this since it's an application bug that can be solved by fixing the content-type, but still might catch some users by surprise.

However, it's more of an issue for apps rendering HTML snippets for inclusion into a full page. For example, using JS to request and inject rendered HTML widgets. Checking "is_xhr" should avoid this for JavaScript XHR requests, though situations where apps send partial-HTML responses that would be screwed up by inserting the toolbar.

So, I'm trying to think about ways to conveniently allow apps to distinguish when it's ok to insert the toolbar if necessary.

**Comment by mgood** [comment]
Maybe just checking if the document starts with `<!doctype html>` is sufficient to determine that it's ok to insert the toolbar at the end, if HTML fragments generally don't include a doctype declaration.

**Comment by mgood** [comment]
Yeah, it didn't seem like it was common to include the `<!doctype html>` declaration in HTML fragment responses, so looking for that also appears that it will be a reasonable sign that it's ok to include the toolbar. So, if the document is missing a `</body>` but starts with `<!doctype html>` (case insensitive) it will append the toolbar.

**Comment by agumonkey** [comment]
Suggesting to include this as a note in the http://flask-debugtoolbar.readthedocs.org/en/latest/ documentation. While testing html-less Flask (rare case I know) I was confused about why no toolbar was showing and spend 10 minutes rereading everything. Thanks for github issues I would never have guessed.
