### ISSUE TITLE
Conflicts with JQUERY : DEBUG_TOOLBAR_STATIC_PATH is not defined

### ISSUE THREAD

**Issue by abdulmuneer** [mgood/flask-debugtoolbar#90]
When a jquery link is added in my template, I get:
```
ReferenceError: DEBUG_TOOLBAR_STATIC_PATH is not defined
$('head').append('<link rel="stylesheet" href="'+DEBUG_TOOLBAR_STATIC_PATH+'css/...
```
I am using jQuery 2.2, but also tried with 1.12 and 1.2.3 which the debug-toolbar is using internally.
I am adding jQuery like this :

```html
<head>
    <link rel="stylesheet" href="{{ url_for('static', filename='css/bootstrap.min.css') }}">
    <script src="{{ url_for('static', filename='js/jquery-2.2.0.min.js') }}" type="text/javascript"/>
    <script src="{{ url_for('static', filename='js/bootstrap.min.js') }}" type="text/javascript"/>
    {% block head %}
    {% endblock %}
    <title>my-title</title>
</head>
```

**Comment by b4stien** [comment]
I had the exact same problem, changing the closing tag solved id, there's obviously something that I don't understand here...

Working:
```
<script type="text/javascript" src="some.js"></script>
<script src="some.js"></script>
```


Not working:
```
<script type="text/javascript" src="some.js" />
<script src="some.js" />
```

(see http://stackoverflow.com/questions/69913/why-dont-self-closing-script-tags-work and probably other resources...)

**Comment by mgood** [comment]
Yeah the Stack Overflow article is correct, you always need to use a `</script>` tag. In HTML5 a closing slash like `<hr />` is basically ignored since it's the same as `<hr>`. It's allowed for authors that need XML compatibility, but it doesn't change the document structure.

To avoid ambiguity, tags like `<script>` that support content need an explicit closing tag.
